Repository GDSC-SWU/2022-02-Web-Dev-Toy-Project-BE, pull requests merged in 2023-02, with the labels that each got.

#41 [5주차] 댓글 알림 API
  app.js
  package-lock.json
  package.json
  prisma/migrations/20230130093141_create_categories/migration.sql
  prisma/schema.prisma
  routes/CommentAlarm.js
  routes/Post.js
Labels: feature

#44 [6주차] 게시글 목록에 place 추가
  routes/Post.js
Labels: feature

#49 [6주차] 게시글 알람 API 수정
  routes/Alarm.js
Labels: refactor

#52 [6주차] 게시글 작성 시 postId 반환
  routes/Post.js
Labels: feature

#53 [6주차] 게시글 수정 API 오류 수정
  routes/Post.js
Labels: bug

#54 [6주차] 게시글 '상세위치' 컬럼 추가 및 API 수정
  package-lock.json
  package.json
  prisma/migrations/20230204144642_create_categories/migration.sql
  prisma/schema.prisma
  routes/Post.js
Labels: feature

#51 [6주차]댓글 API 오류 수정
  app.js
  routes/Comment.js
Labels: bug

#56 [7주차] 게시글 저장시 imagePath가 null인 현상 수정
  util/Storage.js
Labels: bug
