Repository GDSC-SWU/2022-02-Web-Dev-Toy-Project-BE, pull requests merged in 2023-01, with the labels that each got.

#5 1주차 과제
  .gitignore
  app.js
  package-lock.json
  package.json
  prisma/migrations/20221226064422_init/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
Labels: feature

#22 1~3주차 과제 및 모듈화
  .gitignore
  app.js
  middlewares/Auth.js
  middlewares/Multer.js
  package-lock.json
  package.json
  prisma/migrations/20230117180528_init/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  redis/Redis.js
  routes/Auth.js
  routes/Comment.js
  routes/Post.js
  util/Jwt.js
  util/Storage.js
Labels: feature, refactor

#30 [4주차] 알림 API 구현
  app.js
  prisma/schema.prisma
  routes/Alarm.js
Labels: feature

#33 #27 schema 충돌 해결 & migration sql 추가
  prisma/migrations/20230119073212_init/migration.sql
  prisma/schema.prisma
Labels: feature

#27 [4주차] 이메일 인증 시스템 구현
  AuthMail.ejs
  routes/Auth.js
Labels: feature

#32 [4주차] 마이페이지 (작성 게시글/댓글 조회, 닉네임 수정) API 구현
  app.js
  routes/Mypage.js
Labels: feature

#35 4주차 과제
  AuthMail.ejs
  app.js
  prisma/migrations/20230119073212_init/migration.sql
  prisma/schema.prisma
  routes/Alarm.js
  routes/Auth.js
  routes/Mypage.js
Labels: feature

#34 [5주차] object->tag 네이밍 변경
  prisma/migrations/20230120041357_init/migration.sql
  prisma/schema.prisma
  routes/Alarm.js
Labels: refactor

#38 [5주차] 가입완료 response에 누락된 회원 정보 수정
  routes/Auth.js
Labels: bug

#39 [5주차] 마이페이지 API 수정
  routes/Mypage.js
  util/NicknameCheck.js
Labels: feature, refactor

#40 [5주차] 검색 시스템 API 제작
  routes/Post.js
Labels: feature
